// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQyvfbK9I4QWAeIxrYLEC9PEcyxUDByGQ',
    appId: '1:467642481747:web:c7a816c3ad3f7e817f1aa6',
    messagingSenderId: '467642481747',
    projectId: 'restorino-654fe',
    authDomain: 'restorino-654fe.firebaseapp.com',
    databaseURL: 'https://restorino-654fe-default-rtdb.firebaseio.com',
    storageBucket: 'restorino-654fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk9FM-v0Pn48aS9ma7s75n6kD0H-K5Ch8',
    appId: '1:467642481747:android:1d968aa3b9af7cc27f1aa6',
    messagingSenderId: '467642481747',
    projectId: 'restorino-654fe',
    databaseURL: 'https://restorino-654fe-default-rtdb.firebaseio.com',
    storageBucket: 'restorino-654fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT7SpgpGiKS9tiPqbUbRs3XL47fAFrcnw',
    appId: '1:467642481747:ios:43be041f76d4243f7f1aa6',
    messagingSenderId: '467642481747',
    projectId: 'restorino-654fe',
    databaseURL: 'https://restorino-654fe-default-rtdb.firebaseio.com',
    storageBucket: 'restorino-654fe.appspot.com',
    iosClientId: '467642481747-9tojifat3aaeatopren8vn99hp532eqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.restorino',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT7SpgpGiKS9tiPqbUbRs3XL47fAFrcnw',
    appId: '1:467642481747:ios:43be041f76d4243f7f1aa6',
    messagingSenderId: '467642481747',
    projectId: 'restorino-654fe',
    databaseURL: 'https://restorino-654fe-default-rtdb.firebaseio.com',
    storageBucket: 'restorino-654fe.appspot.com',
    iosClientId: '467642481747-9tojifat3aaeatopren8vn99hp532eqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.restorino',
  );
}
